-- ============================================================
-- TALLER MOTOS — Schema inicial
-- ============================================================

create extension if not exists pgcrypto;

-- ── USUARIOS ─────────────────────────────────────────────────
create table if not exists public.user_profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text not null unique,
  username    text not null unique,
  nombre      text not null,
  rol         text not null check (rol in ('ADMIN', 'MECANICO')),
  -- solo para mecánicos
  tipo_sueldo text check (tipo_sueldo in ('FIJO', 'COMISION')),
  sueldo_base numeric(10,2),   -- monto fijo mensual o base de comisión
  activo      boolean not null default true,
  creado_en   timestamptz not null default now()
);

-- ── INSUMOS (repuestos / piezas del inventario) ───────────────
create table if not exists public.insumos (
  id        bigint generated by default as identity primary key,
  nombre    text not null,
  precio    numeric(10,2) not null default 0,
  stock     integer not null default 0,
  activo    boolean not null default true,
  creado_en timestamptz not null default now()
);

-- ── CARDS (órdenes de trabajo) ────────────────────────────────
create table if not exists public.cards (
  id              bigint generated by default as identity primary key,
  cliente_nombre  text not null,
  cliente_telefono text,
  fecha           date not null default current_date,
  tipo_servicio   text not null check (tipo_servicio in (
    'MANTENIMIENTO_BASICO',
    'MANTENIMIENTO_COMPLETO',
    'CAMBIO_ACEITE',
    'REPARACION_TELESCOPIO'
  )),
  estado          text not null default 'NUEVO' check (estado in (
    'NUEVO', 'EN_CURSO', 'PAUSADO', 'TERMINADO', 'PRUEBAS', 'FINALIZADO'
  )),
  mecanico_id     uuid references public.user_profiles(id),
  notas           text,
  creado_en       timestamptz not null default now(),
  actualizado_en  timestamptz not null default now()
);

-- ── REEMPLAZOS (insumos usados en una card) ──────────────────
create table if not exists public.reemplazos (
  id        bigint generated by default as identity primary key,
  card_id   bigint not null references public.cards(id) on delete cascade,
  insumo_id bigint references public.insumos(id),
  nombre    text not null,   -- snapshot del nombre
  precio    numeric(10,2) not null,
  cantidad  integer not null default 1,
  creado_en timestamptz not null default now()
);

-- ── TRABAJOS EXTERNOS ─────────────────────────────────────────
create table if not exists public.trabajos_externos (
  id          bigint generated by default as identity primary key,
  card_id     bigint not null references public.cards(id) on delete cascade,
  detalle     text not null,
  precio_final numeric(10,2) not null,
  costo        numeric(10,2) not null default 0,
  creado_en   timestamptz not null default now()
);

-- ── SERVICIOS REALIZADOS (mano de obra del mecánico en la card) ─
create table if not exists public.servicios_realizados (
  id          bigint generated by default as identity primary key,
  card_id     bigint not null references public.cards(id) on delete cascade,
  nombre      text not null,
  descripcion text,
  precio      numeric(10,2) not null default 0,
  creado_en   timestamptz not null default now()
);

-- ── TRABAJOS REALIZADOS (log de movimientos de estado) ────────
create table if not exists public.trabajos_realizados (
  id          bigint generated by default as identity primary key,
  card_id     bigint not null references public.cards(id) on delete cascade,
  mecanico_id uuid references public.user_profiles(id),
  estado_desde text,
  estado_hasta text not null,
  nota         text,
  creado_en   timestamptz not null default now()
);

-- ── ÍNDICES ───────────────────────────────────────────────────
create index if not exists idx_cards_estado       on public.cards(estado);
create index if not exists idx_cards_mecanico     on public.cards(mecanico_id);
create index if not exists idx_cards_fecha        on public.cards(fecha);
create index if not exists idx_reemplazos_card    on public.reemplazos(card_id);
create index if not exists idx_trabajos_ext_card  on public.trabajos_externos(card_id);
create index if not exists idx_trab_real_card     on public.trabajos_realizados(card_id);
create index if not exists idx_insumos_activo     on public.insumos(activo);
create index if not exists idx_serv_real_card     on public.servicios_realizados(card_id);

-- ── PRECIOS DE SERVICIO POR DEFECTO ──────────────────────────
create table if not exists public.config (
  key   text primary key,
  value text not null
);

-- config sin precios fijos (los montos vienen de servicios_realizados, reemplazos y trabajos_externos)

-- ── RLS básico: habilitar (las políticas se agregan según necesidad) ─
alter table public.user_profiles     enable row level security;
alter table public.insumos           enable row level security;
alter table public.cards             enable row level security;
alter table public.reemplazos        enable row level security;
alter table public.trabajos_externos enable row level security;
alter table public.trabajos_realizados enable row level security;
alter table public.servicios_realizados enable row level security;
alter table public.config            enable row level security;

-- Política abierta para el service_role (Worker usa service key)
create policy "service_role_all" on public.user_profiles     for all using (true);
create policy "service_role_all" on public.insumos           for all using (true);
create policy "service_role_all" on public.cards             for all using (true);
create policy "service_role_all" on public.reemplazos        for all using (true);
create policy "service_role_all" on public.trabajos_externos for all using (true);
create policy "service_role_all" on public.trabajos_realizados for all using (true);
create policy "service_role_all" on public.servicios_realizados  for all using (true);
create policy "service_role_all" on public.config            for all using (true);
