-- ============================================================
-- NOTIFICACIONES — Migration 002
-- ============================================================

-- Notificaciones in-app
create table if not exists public.notificaciones (
  id          bigint generated by default as identity primary key,
  usuario_id  uuid references public.user_profiles(id) on delete cascade,
  tipo        text not null default 'ESTADO', -- 'ESTADO' | 'SISTEMA'
  titulo      text not null,
  cuerpo      text not null,
  card_id     bigint references public.cards(id) on delete set null,
  leida       boolean not null default false,
  creado_en   timestamptz not null default now()
);

create index if not exists idx_notif_usuario on public.notificaciones(usuario_id);
create index if not exists idx_notif_leida   on public.notificaciones(leida);
create index if not exists idx_notif_fecha   on public.notificaciones(creado_en desc);

-- Suscripciones Web Push (una por dispositivo/usuario)
create table if not exists public.push_subscriptions (
  id          bigint generated by default as identity primary key,
  usuario_id  uuid references public.user_profiles(id) on delete cascade,
  endpoint    text not null unique,
  p256dh      text not null,
  auth_key    text not null,
  user_agent  text,
  creado_en   timestamptz not null default now()
);

create index if not exists idx_push_usuario on public.push_subscriptions(usuario_id);

-- RLS
alter table public.notificaciones      enable row level security;
alter table public.push_subscriptions  enable row level security;

create policy "service_role_all" on public.notificaciones     for all using (true);
create policy "service_role_all" on public.push_subscriptions for all using (true);

-- Habilitar Realtime en notificaciones (ejecutar en Supabase Dashboard también)
-- alter publication supabase_realtime add table public.notificaciones;
