-- ============================================================
-- TALLER MOTOS — Migration 003
-- Eliminar precio_servicio de cards
-- Crear tabla servicios_realizados (trabajos de mano de obra)
-- ============================================================

-- 1. Nueva tabla: servicios realizados (mano de obra / trabajos del mecánico)
create table if not exists public.servicios_realizados (
  id          bigint generated by default as identity primary key,
  card_id     bigint not null references public.cards(id) on delete cascade,
  nombre      text not null,         -- ej: "Cambio de aceite", "Ajuste de frenos"
  descripcion text,                  -- detalle opcional
  precio      numeric(10,2) not null default 0,
  creado_en   timestamptz not null default now()
);

create index if not exists idx_serv_real_card on public.servicios_realizados(card_id);

alter table public.servicios_realizados enable row level security;
create policy "service_role_all" on public.servicios_realizados for all using (true);

-- 2. Quitar precio_servicio de cards (ya no se usa)
--    Si ya existe la columna la eliminamos; si no, ignoramos el error
alter table public.cards drop column if exists precio_servicio;

-- 3. Eliminar config de precios fijos (ya no aplica)
delete from public.config where key like 'precio_%';

-- 4. Habilitar Realtime para notificaciones (ejecutar también en Dashboard)
-- alter publication supabase_realtime add table public.servicios_realizados;
