-- ============================================================
-- TALLER MOTOS — Migration 004
-- ============================================================

-- 1. Quitar estado PAUSADO del check constraint
ALTER TABLE public.cards DROP CONSTRAINT IF EXISTS cards_estado_check;
ALTER TABLE public.cards ADD CONSTRAINT cards_estado_check
  CHECK (estado IN ('NUEVO', 'EN_CURSO', 'TERMINADO', 'PRUEBAS', 'FINALIZADO'));

-- Actualizar cards que estén en PAUSADO a EN_CURSO
UPDATE public.cards SET estado = 'EN_CURSO' WHERE estado = 'PAUSADO';

-- 2. Cambiar sueldo_base a sueldo_semanal en user_profiles
ALTER TABLE public.user_profiles RENAME COLUMN sueldo_base TO sueldo_semanal;

-- 3. Agregar costo a reemplazos (cuánto le costó al taller el repuesto)
ALTER TABLE public.reemplazos ADD COLUMN IF NOT EXISTS costo numeric(10,2) NOT NULL DEFAULT 0;

-- 4. Tabla de compras / consumibles (salida de caja)
CREATE TABLE IF NOT EXISTS public.compras (
  id          bigint generated by default as identity primary key,
  descripcion text NOT NULL,
  categoria   text NOT NULL DEFAULT 'CONSUMIBLE' CHECK (categoria IN (
    'CONSUMIBLE', 'REPUESTO', 'HERRAMIENTA', 'INSUMO', 'OTRO'
  )),
  cantidad    integer NOT NULL DEFAULT 1,
  costo_unit  numeric(10,2) NOT NULL DEFAULT 0,
  costo_total numeric(10,2) GENERATED ALWAYS AS (cantidad * costo_unit) STORED,
  proveedor   text,
  notas       text,
  fecha       date NOT NULL DEFAULT current_date,
  registrado_por uuid REFERENCES public.user_profiles(id),
  creado_en   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_compras_fecha     ON public.compras(fecha);
CREATE INDEX IF NOT EXISTS idx_compras_categoria ON public.compras(categoria);

ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_all" ON public.compras FOR ALL USING (true);

-- 5. Tipo de servicio múltiple: cambiar de text a text[] en cards
-- Primero convertir el valor existente a array
ALTER TABLE public.cards ALTER COLUMN tipo_servicio TYPE text[] USING ARRAY[tipo_servicio];
ALTER TABLE public.cards ALTER COLUMN tipo_servicio SET DEFAULT '{}';
ALTER TABLE public.cards DROP CONSTRAINT IF EXISTS cards_tipo_servicio_check;
